# Generated by Django 6.0 on 2026-01-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BSc', 'BSc'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('BCOM', 'BCOM'), ('BBA', 'BBA')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
