# Generated by Django 6.0 on 2026-01-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BSc IT', 'BSc IT'), ('BBM', 'BBM'), ('BSc Microbiology', 'BSc Microbiology'), ('BA English', 'BA English'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('BCOM', 'BCOM'), ('BBA', 'BBA')], max_length=50),
        ),
    ]
